### ISSUE TITLE
System.UnauthorizedAccessException when deleting folder during --upgrade-all

### ISSUE THREAD

**Issue by hach-que** [Protobuild/Protobuild#168]
```
1	(1/10) HTTP GET http://protobuild.org/hach-que/Protogame/api
2	Package type not specified (and no file at Protogame\.git), requesting binary version.
3	Creating and emptying Protogame\Windows
4	System.UnauthorizedAccessException: Access to the path 'c:\var\drydock\workingcopy-64\repo\minute-of-mayhem\Protogame\Windows\MonoGame\.git\objects\pack\pack-fc5607b06c95efc3f0518d3882068d96df0b399e.idx' is denied.
5	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
6	   at System.IO.File.InternalDelete(String path, Boolean checkHost)
7	   at Protobuild.PathUtils.AggressiveDirectoryDelete(String directory)
8	   at Protobuild.PathUtils.AggressiveDirectoryDelete(String directory)
9	   at Protobuild.PathUtils.AggressiveDirectoryDelete(String directory)
10	   at Protobuild.PathUtils.AggressiveDirectoryDelete(String directory)
11	   at Protobuild.PathUtils.AggressiveDirectoryDelete(String directory)
12	   at Protobuild.BinaryPackageResolve.ResolveLibraryBinary(ICachableBinaryPackageMetadata protobuildMetadata, String folder, Boolean forceUpgrade, Func`1 getBinaryPackage)
13	   at Protobuild.Internal.ProtobuildPackageProtocol.<ResolveSource>b__6_0(IPackageMetadata metadata, String folder, String name, Boolean upgrade, Nullable`1 source)
14	   at Protobuild.PackageManager.Resolve(IPackageMetadata metadata, PackageRef reference, String templateName, Nullable`1 source, Boolean forceUpgrade)
15	   at Protobuild.PackageManager.Resolve(ModuleInfo module, PackageRef reference, String platform, String templateName, Nullable`1 source, Boolean forceUpgrade)
16	   at Protobuild.UpgradeAllPackagesCommand.Execute(Execution execution)
17	   at Protobuild.MainClass.Main(String[] args)
```

Folder deletion should be handled more gracefully (by retrying with exponential timeouts).

**Comment by hach-que** [comment]
This should be mitigated somewhat in 0b21b85.
