### ISSUE TITLE
Protobuild.exe --start throws 404 Not Found

### ISSUE THREAD

**Issue by andrekoehler** [Protobuild/Protobuild#263]
```
D:\dev\_tests\foo>Protobuild.exe --start http://protobuild.org/commons/Console helloWorld
(1/10) HTTP GET http://protobuild.org/commons/Console/api
Exception during web request:
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Protobuild.RetryableWebClient.PerformRetryableRequest[T](String message, Uri baseUri, Func`2 func)
Backing off web requests for 0ms...
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Protobuild.RetryableWebClient.PerformRetryableRequest[T](String message, Uri baseUri, Func`2 func)
   --- End of inner exception stack trace ---
   at Protobuild.RetryableWebClient.PerformRetryableRequest[T](String message, Uri baseUri, Func`2 func)
   at Protobuild.RetryableWebClient.DownloadString(Uri uri)
   at Protobuild.Internal.ProtobuildPackageProtocol.GetJSON(Uri indexUri, String& str)
   at Protobuild.Internal.ProtobuildPackageProtocol.ResolveSource(String workingDirectory, PackageRequestRef request)
   at Protobuild.PackageLookup.Lookup(String workingDirectory, PackageRequestRef request)
   at Protobuild.PackageManager.Lookup(String workingDirectory, ModuleInfo module, PackageRef reference, String platform, String templateName, Nullable`1 source, Boolean forceUpgrade, Nullable`1 safeResolve)
   at Protobuild.PackageManager.Resolve(String workingDirectory, ModuleInfo module, PackageRef reference, String platform, String templateName, Nullable`1 source, Boolean forceUpgrade, Nullable`1 safeResolve)
   at Protobuild.StartCommand.Execute(Execution execution)
   at Protobuild.MainClass.Main(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Protobuild.RetryableWebClient.PerformRetryableRequest[T](String message, Uri baseUri, Func`2 func)<---
```

**Comment by hach-que** [comment]
The Protobuild Index is no longer available. You need to use NuGet instead.

Try this:

```
Protobuild.exe --install Protobuild.Template.Console
```

**Comment by hach-que** [comment]
Closing this issue as the steps above should resolve. Please re-open if you experience any issues relating to the suggested command.
